# Generated by Django 5.2.9 on 2025-12-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('state', models.CharField(max_length=100)),
                ('architectural_style', models.CharField(max_length=100)),
                ('year_built', models.CharField(blank=True, max_length=50)),
                ('description_short', models.TextField()),
            ],
        ),
    ]
