# Generated by Django 5.2.9 on 2025-12-29 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monuments', '0002_periods'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitecturalStyle',
            fields=[
                ('style_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'architectural_style',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'location',
                'unique_together': {('city', 'state')},
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'period',
            },
        ),
        migrations.DeleteModel(
            name='Periods',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='architectural_style',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='description_short',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='id',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='state',
        ),
        migrations.RemoveField(
            model_name='monument',
            name='year_built',
        ),
        migrations.AddField(
            model_name='monument',
            name='monument_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monument',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='monument',
            table='monument',
        ),
        migrations.AddField(
            model_name='monument',
            name='style',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='monuments.architecturalstyle'),
        ),
        migrations.AddField(
            model_name='monument',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monuments', to='monuments.location'),
        ),
        migrations.AddField(
            model_name='monument',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monuments', to='monuments.period'),
        ),
    ]
