# Generated by Django 5.2.9 on 2026-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "monuments",
            "0003_architecturalstyle_location_period_delete_periods_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="architecturalstyle",
            name="monument_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="zone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monument",
            name="monument_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monument",
            name="year",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="monument",
            name="zone",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="period",
            name="year",
            field=models.TextField(unique=True),
        ),
    ]
